<?php

namespace Omnipay\IPay88\Message;


use Omnipay\Common\Message\AbstractResponse;
use Omnipay\Common\Message\RequestInterface;

class CompletePurchaseResponse extends AbstractResponse
{
    protected $reQueryResponse = [
        '00' => 'Successful payment',
        'Invalid parameters' => 'Parameters pass in incorrect',
        'Record not found' => 'Cannot found the record',
        'Incorrect amount' => 'Amount different',
        'Payment fail' => 'Payment fail',
        'M88Admin' => 'Payment status updated by iPay88 Admin(Fail)'
    ];

    protected $invalidSignatureMsg = 'Invalid signature returned from iPay88';

    protected $message;

    protected $status;

    public function __construct(RequestInterface $request, $data)
    {
        parent::__construct($request, $data);

        // This is important and need to put on top, 
        // to make sure the request is not generated by hackers
        if ($this->data['Signature'] != $this->data['ComputedSignature']) {
            $this->message = $this->invalidSignatureMsg;
            $this->status = false;
            return;
        }

        if ($this->data['Status'] != 1) {
            $this->message = $this->data['ErrDesc'];
            $this->status = false;
            return;
        }

        $this->message = '';

        if (isset($this->data['ReQueryStatus'])) {
            $this->message =
            isset($this->reQueryResponse[$this->data['ReQueryStatus']]) ? $this->reQueryResponse[$this->data['ReQueryStatus']] : '';

            if ('00' == $this->data['ReQueryStatus']) {
                $this->status = true;
                return;
            }
            
            if ('Limited by per day maximum number of requery' == $this->data['ReQueryStatus'] && $this->data['Status'] == 1 ) {
                $this->status = true;
                return;
            }
        } else if ($this->data['Status'] == 1) {
            $this->status = true;
            return;
        }

        $this->status = false;
        return;
    }

    public function isSuccessful()
    {
        return $this->status;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function getTransactionReference()
    {
        return $this->data['TransId'];
    }

    public function getTransactionId()
    {
        return $this->data['RefNo'];
    }

}